on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          default-branch: main

  package:
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/shared/setup'
      - run: npm run build
      - run: npm pack
      - run: echo "package_version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: mktable-${{ steps.vars.outputs.package_version }}
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: '*.tgz'
