on:
   push:
     branches:
       - main
name: release-please
permissions: {}
jobs:
  release-please:
    outputs:
      releases_created: ${{steps.release.outputs.releases_created}}
    permissions:
      contents: write # to create release commit (google-github-actions/release-please-action)
      pull-requests: write # to create release PR (google-github-actions/release-please-action)

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          default-branch: main
          release-type: node
          package-name: mktable
      - uses: actions/checkout@v3
      - uses: './.github/shared/setup'
  publish:
      needs: [release-please]
      if: needs.release-please.outputs.releases_created
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
        packages: read
      steps:
      - uses: actions/checkout@v3
      - uses: './.github/shared/setup'
      - run: npm run build
      - run: npm publish
        env:
          NPM_PERSONAL_AUTH_TOKEN: ${{secrets.NPM_PERSONAL_ACCESS_TOKEN}}
