name: Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/shared/setup'
      - name: Lint & Typecheck
        run: npm run typecheck && npm run lint
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/shared/setup'
      - name: Test
        run: npm run test
